from __future__ import annotations

import sys
import time
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

ROOT_DIR = Path(__file__).resolve().parents[1]
if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))

MODULES_TO_RESET = [
    "app",
    "app.main",
    "app.routes",
    "app.queue_worker",
    "app.auth",
    "app.models",
    "app.database",
]


@pytest.fixture()
def client(tmp_path, monkeypatch):
    monkeypatch.setenv("DATABASE_URL", f"sqlite:///{tmp_path / 'test_geo_furniture.db'}")
    monkeypatch.setenv("SECRET_KEY", "test-secret-key")

    for module_name in MODULES_TO_RESET:
        sys.modules.pop(module_name, None)

    from app.main import app

    with TestClient(app) as test_client:
        yield test_client


def auth_headers(client: TestClient, username: str, password: str) -> dict[str, str]:
    response = client.post("/login", json={"username": username, "password": password})
    assert response.status_code == 200, response.text
    token = response.json()["access_token"]
    return {"Authorization": f"Bearer {token}"}


def test_demo_accounts_can_login(client: TestClient):
    for username, password in [
        ("admin", "admin123"),
        ("customer", "customer123"),
        ("warehouse", "warehouse123"),
    ]:
        response = client.post("/login", json={"username": username, "password": password})
        assert response.status_code == 200
        body = response.json()
        assert body["access_token"]
        assert body["user"]["username"] == username


def test_customer_can_create_order_and_receive_notification(client: TestClient):
    headers = auth_headers(client, "customer", "customer123")
    create_response = client.post(
        "/orders",
        headers=headers,
        json={
            "product_type": "Compact Nightstand",
            "quantity": 2,
            "price": 145.0,
            "latitude": 43.238949,
            "longitude": 76.889709,
            "notes": "Handle with care.",
        },
    )
    assert create_response.status_code == 201, create_response.text
    order_id = create_response.json()["id"]

    orders_response = client.get("/orders", headers=headers)
    assert orders_response.status_code == 200
    assert any(order["id"] == order_id for order in orders_response.json())

    for _ in range(8):
        logs_response = client.get("/audit-logs", headers=headers, params={"limit": 30})
        assert logs_response.status_code == 200
        if any(
            log["action"] == "warehouse_notification" and log["target_id"] == order_id
            for log in logs_response.json()
        ):
            break
        time.sleep(0.2)
    else:
        pytest.fail("warehouse notification was not generated by the queue worker")


def test_warehouse_manager_only_sees_assigned_region(client: TestClient):
    headers = auth_headers(client, "warehouse", "warehouse123")
    me_response = client.get("/me", headers=headers)
    assert me_response.status_code == 200
    allowed_region = me_response.json()["allowed_h3_region"]

    orders_response = client.get("/orders", headers=headers)
    assert orders_response.status_code == 200
    orders = orders_response.json()
    assert orders
    assert all(order["h3_region"] == allowed_region for order in orders)


def test_order_validation_rejects_invalid_quantity(client: TestClient):
    headers = auth_headers(client, "customer", "customer123")
    response = client.post(
        "/orders",
        headers=headers,
        json={
            "product_type": "Invalid Chair",
            "quantity": 0,
            "price": 20.0,
            "latitude": 43.238949,
            "longitude": 76.889709,
        },
    )
    assert response.status_code == 422
